---
- name: Secure segment network traffic
  hosts: [controlnode1, controlnode2]
  become: true

  tasks:
  - name: UFW - Enable and deny by default
    community.general.ufw:
      state: enabled
      default: deny

  - name: Allow OpenSSH traffic
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: Allow traffic on specific port
    community.general.ufw:
      rule: allow
      port: 8080

  - name: Allow traffic from specific IP
    community.general.ufw:
      rule: allow
      src: 192.168.1.100

  - name: Reload UFW
    community.general.ufw:
      state: reloaded
